### ISSUE TITLE
自定义规则问题

### ISSUE THREAD

**Issue by ladyboys** [gkd-kit/docs#4]
自定义规则上手难度大，可以参考一下李跳跳，扫描本地安装的软件，然后进一步做自定义规则

**Comment by lisonge** [comment]
你好，你可以自己做一个网页来解析快照文件并生成规则，这样大家都能用了

**Comment by ladyboys** [comment]
我就是因为不太会，不知道快照功能是什么意思，该怎么使用








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年4月7日(周日) 上午9:37写道:

  

 
你好，你可以自己做一个网页来解析快照文件并生成规则，这样大家都能用了

**Comment by lisonge** [comment]
快照 是保存当前屏幕截图和所有节点信息 得到的一个 zip 文件

将这个 zip 文件上传后会得到一个类似 <https://i.gkd.li/i/14881985> 的链接

这个界面就是快照的具体可视化界面

**Comment by adproqwq** [comment]
实在不行我倒是写了个李跳跳规则转GKD规则的，你去用吧
[网站](https://ltt2gkd.adproqwq.xyz)

**Comment by lisonge** [comment]
他的意思应该是 GKD 应该给 每个应用 默认情况下 有一些规则给用户使用

但是现在 GKD 默认不携带任何规则，所以这个默认行为是不能实现的

但是这个操作可以通过添加一些默认不启用的全局规则实现

**Comment by adproqwq** [comment]
> 但是这个操作可以通过添加一些默认不启用的全局规则实现

这种情况就需要添加第三方的订阅，因为默认订阅停止维护且也只有开屏广告一条全局。但是我看他的意思更像是想要自己写规则，但是觉得太难。想要GKD像李跳跳那样的傻瓜式（相对GKD而言）那样简单的自定义规则方式。

**Comment by ladyboys** [comment]
是的，想自己写，但太难，想和李跳跳一样的傻瓜式发自我的手机-------- 原始邮件 --------发件人： 二刺螈 ***@***.***>日期： 2024年4月7日周日 17:24收件人： gkd-kit/docs ***@***.***>抄送： ladyboys ***@***.***>, Author ***@***.***>主    题： Re: [gkd-kit/docs] 自定义规则问题 (Issue #4)
他的意思应该是 GKD 应该给 每个应用 默认情况下 有一些规则给用户使用
但是现在 GKD 默认不携带任何规则，所以这个默认行为是不能实现的
但是这个操作可以通过添加一些默认不启用的全局规则实现

**Comment by ladyboys** [comment]
你做的转换网站好像没有反应，不能转换，也导出不了，要不你再试试？发自我的手机-------- 原始邮件 --------发件人： Adpro ***@***.***>日期： 2024年4月7日周日 17:21收件人： gkd-kit/docs ***@***.***>抄送： ladyboys ***@***.***>, Author ***@***.***>主    题： Re: [gkd-kit/docs] 自定义规则问题 (Issue #4)
实在不行我倒是写了个李跳跳规则转GKD规则的，你去用吧
网站

**Comment by adproqwq** [comment]
> 你做的转换网站好像没有反应，不能转换，也导出不了，要不你再试试？

你确认下格式问题？用中括号包裹住所有应用的规则，类似[{},{},{}...]这样的样子。
如果还是不行，可以试下用梯子。还是不行再跟我说

**Comment by HandsomeGXB** [comment]
自定义规则的学习可以参考这里：https://github.com/Snoopy1866/blogs/blob/main/software/gkd/gkd-rule-tutorial/gkd-rule-tutorial.md
